//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Web.Services.WebServiceBindingAttribute(Name="WsMoneyGramTISoapBinding", Namespace="http://10.81.9.32:7777/WsMoneyGramTI/services/WsMoneyGramTI")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(OperationField))]
public interface IWsMoneyGramTISoapBinding {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cliente.Com", ResponseNamespace="http://10.81.9.32:7777/WsMoneyGramTI/services/WsMoneyGramTI")]
    [return: System.Xml.Serialization.SoapElementAttribute("sendRequestReturn")]
    ResponseData sendRequest(RequestData request);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cliente.Com", ResponseNamespace="http://10.81.9.32:7777/WsMoneyGramTI/services/WsMoneyGramTI")]
    [return: System.Xml.Serialization.SoapElementAttribute("getAgentInformationReturn")]
    AgentInfoResponse getAgentInformation(AgentInfoRequest informacionIN);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cliente.Com", ResponseNamespace="http://10.81.9.32:7777/WsMoneyGramTI/services/WsMoneyGramTI")]
    [return: System.Xml.Serialization.SoapElementAttribute("getTransactionNamesReturn")]
    string[] getTransactionNames(string UID);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cliente.Com", ResponseNamespace="http://10.81.9.32:7777/WsMoneyGramTI/services/WsMoneyGramTI")]
    [return: System.Xml.Serialization.SoapElementAttribute("getInputFieldNamesReturn")]
    string[] getInputFieldNames(string UID, string transaction);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:RR")]
public partial class RequestData {
    
    private string uIDField;
    
    private OperationField[] arrField;
    
    private string operationNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string UID {
        get {
            return this.uIDField;
        }
        set {
            this.uIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OperationField[] arr {
        get {
            return this.arrField;
        }
        set {
            this.arrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string operationName {
        get {
            return this.operationNameField;
        }
        set {
            this.operationNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:RR")]
public partial class OperationField {
    
    private string fieldNameField;
    
    private string fieldValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string fieldName {
        get {
            return this.fieldNameField;
        }
        set {
            this.fieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string fieldValue {
        get {
            return this.fieldValueField;
        }
        set {
            this.fieldValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:RR")]
public partial class AgentInfoResponse {
    
    private string uIDField;
    
    private string agentIDField;
    
    private string agentSequenceField;
    
    private string apiVersionField;
    
    private string clientSoftwareVersionField;
    
    private string mensageField;
    
    private string tokenField;
    
    private string unitProfileField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string UID {
        get {
            return this.uIDField;
        }
        set {
            this.uIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string agentID {
        get {
            return this.agentIDField;
        }
        set {
            this.agentIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string agentSequence {
        get {
            return this.agentSequenceField;
        }
        set {
            this.agentSequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string apiVersion {
        get {
            return this.apiVersionField;
        }
        set {
            this.apiVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string clientSoftwareVersion {
        get {
            return this.clientSoftwareVersionField;
        }
        set {
            this.clientSoftwareVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string mensage {
        get {
            return this.mensageField;
        }
        set {
            this.mensageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string token {
        get {
            return this.tokenField;
        }
        set {
            this.tokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string unitProfile {
        get {
            return this.unitProfileField;
        }
        set {
            this.unitProfileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:RR")]
public partial class AgentInfoRequest {
    
    private string uIDField;
    
    private int canalField;
    
    private int paisField;
    
    private int sucursalField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string UID {
        get {
            return this.uIDField;
        }
        set {
            this.uIDField = value;
        }
    }
    
    /// <remarks/>
    public int canal {
        get {
            return this.canalField;
        }
        set {
            this.canalField = value;
        }
    }
    
    /// <remarks/>
    public int pais {
        get {
            return this.paisField;
        }
        set {
            this.paisField = value;
        }
    }
    
    /// <remarks/>
    public int sucursal {
        get {
            return this.sucursalField;
        }
        set {
            this.sucursalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:RR")]
public partial class ResponseData {
    
    private string uIDField;
    
    private OperationField[] arrField;
    
    private bool exitoField;
    
    private string mensajeErrorField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string UID {
        get {
            return this.uIDField;
        }
        set {
            this.uIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public OperationField[] arr {
        get {
            return this.arrField;
        }
        set {
            this.arrField = value;
        }
    }
    
    /// <remarks/>
    public bool exito {
        get {
            return this.exitoField;
        }
        set {
            this.exitoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string mensajeError {
        get {
            return this.mensajeErrorField;
        }
        set {
            this.mensajeErrorField = value;
        }
    }
}
